apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
       app: python-app
  template:
    metadata:
      name: python-app
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: ashishsigmoid/pod_info:latest
          imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: python-app
spec:
  type: LoadBalancer
  selector:
    app: python-app
  ports:
   - name: metrics
     port: 6060
     targetPort: 6060
