apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
       app: flask-app
  template:
    metadata:
      name: flask-app
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: ashishsigmoid/python-application:latest
          imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service
metadata:
  name: flask-app
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
   - name: http
     port: 5000
     targetPort: 5000
