global:
  scrape_interval:     5s
  evaluation_interval: 30s
scrape_configs:
- job_name: my-application
  honor_labels: true
  static_configs:
          - targets: ['localhost:5000']

- job_name: pod-info
  honor_labels: true
  static_configs:
          - targets: ['192.168.1.10:31541']
